sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

before_install:
  - bash scripts/install_sfml.sh
  - bash scripts/install_lua.sh

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang
    - glew-utils
    - libglew-dev
    - libudev-dev
    - libjpeg-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./Test